static const std::map<std::string, std::string> cntl_msg_map = {
	{"AePrecaptureTrigger", "AePrecaptureTrigger\n\nControl for A"
		"E metering trigger. Currently identical to\nANDROID_CONTROL_"
		"AE_PRECAPTURE_TRIGGER.\n\nWhether the camera device will tri"
		"gger a precapture metering sequence\nwhen it processes this "
		"request.\n0\tThe trigger is idle.\n1\tThe pre-capture AE met"
		"ering is started by the camera.\n2\tThe camera will cancel a"
		"ny active or completed metering sequence.\n\tThe AE algorith"
		"m is reset to its initial state.\n"},
	{"NoiseReductionMode", "NoiseReductionMode\n\nControl to sele"
		"ct the noise reduction algorithm mode. Currently\nidentical "
		"to ANDROID_NOISE_REDUCTION_MODE.\n\n Mode of operation for t"
		"he noise reduction algorithm.\n0\tNo noise reduction is appl"
		"ied\n1\tNoise reduction is applied without reducing the fram"
		"e rate.\n2\tHigh quality noise reduction at the expense of f"
		"rame rate.\n3\tMinimal noise reduction is applied without re"
		"ducing the frame rate.\n4\tNoise reduction is applied at dif"
		"ferent levels to different streams.\n"},
	{"ColorCorrectionAberrationMode", "ColorCorrectionAberrationM"
		"ode\n\nControl to select the color correction aberration mod"
		"e. Currently\nidentical to ANDROID_COLOR_CORRECTION_ABERRATI"
		"ON_MODE.\n\n Mode of operation for the chromatic aberration "
		"correction algorithm.\n0\tNo aberration correction is applie"
		"d.\n1\tAberration correction will not slow down the frame ra"
		"te.\n2\tHigh quality aberration correction which might reduc"
		"e the frame\n\trate.\n"},
	{"LensShadingMapMode", "LensShadingMapMode\n\nControl to repo"
		"rt if the lens shading map is available. Currently\nidentica"
		"l to ANDROID_STATISTICS_LENS_SHADING_MAP_MODE.\n0\tNo lens s"
		"hading map mode is available.\n1\tThe lens shading map mode "
		"is available.\n"},
	{"TestPatternMode", "TestPatternMode\n\nControl to select the"
		" test pattern mode. Currently identical to\nANDROID_SENSOR_T"
		"EST_PATTERN_MODE.\n0\tNo test pattern mode is used. The came"
		"ra device returns frames from\n\tthe image sensor.\n1\tEach "
		"pixel in [R, G_even, G_odd, B] is replaced by its respective"
		"\n\tcolor channel provided in test pattern data.\n\t\todo Ad"
		"d control for test pattern data.\n2\tAll pixel data is repla"
		"ced with an 8-bar color pattern. The vertical\n\tbars (left-"
		"to-right) are as follows; white, yellow, cyan, green,\n\tmag"
		"enta, red, blue and black. Each bar should take up 1/8 of th"
		"e\n\tsensor pixel array width. When this is not possible, th"
		"e bar size\n\tshould be rounded down to the nearest integer "
		"and the pattern can\n\trepeat on the right side. Each bar's "
		"height must always take up the\n\tfull sensor pixel array he"
		"ight.\n3\tThe test pattern is similar to TestPatternModeColo"
		"rBars,\n\texcept that each bar should start at its specified"
		" color at the top\n\tand fade to gray at the bottom. Further"
		"more each bar is further\n\tsubdevided into a left and right"
		" half. The left half should have a\n\tsmooth gradient, and t"
		"he right half should have a quantized\n\tgradient. In partic"
		"ular, the right half's should consist of blocks\n\tof the sa"
		"me color for 1/16th active sensor pixel array width. The\n\t"
		"least significant bits in the quantized gradient should be c"
		"opied\n\tfrom the most significant bits of the smooth gradie"
		"nt. The height of\n\teach bar should always be a multiple of"
		" 128. When this is not the\n\tcase, the pattern should repea"
		"t at the bottom of the image.\n4\tAll pixel data is replaced"
		" by a pseudo-random sequence generated\n\tfrom a PN9 512-bit"
		" sequence (typically implemented in hardware with\n\ta linea"
		"r feedback shift register). The generator should be reset at"
		"\n\tthe beginning of each frame, and thus each subsequent ra"
		"w frame with\n\tthis test pattern should be exactly the same"
		" as the last.\n256\tThe first custom test pattern. All custo"
		"m patterns that are\n\tavailable only on this camera device "
		"are at least this numeric\n\tvalue. All of the custom test p"
		"atterns will be static (that is the\n\traw image must not va"
		"ry from frame to frame).\n"},
	{"FaceDetectMode", "FaceDetectMode\n\nControl to select the f"
		"ace detection mode used by the pipeline.\n\nCurrently identi"
		"cal to ANDROID_STATISTICS_FACE_DETECT_MODE.\n\nSee also: Fac"
		"eDetectFaceRectangles\nSee also: FaceDetectFaceScores\nSee a"
		"lso: FaceDetectFaceLandmarks\nSee also: FaceDetectFaceIds\n0"
		"\tPipeline doesn't perform face detection and doesn't report"
		" any\n\tcontrol related to face detection.\n1\tPipeline perf"
		"orms face detection and reports the\n\tFaceDetectFaceRectang"
		"les and FaceDetectFaceScores controls for each\n\tdetected f"
		"ace. FaceDetectFaceLandmarks and FaceDetectFaceIds are\n\top"
		"tional.\n2\tPipeline performs face detection and reports all"
		" the controls\n\trelated to face detection including FaceDet"
		"ectFaceRectangles,\n\tFaceDetectFaceScores, FaceDetectFaceLa"
		"ndmarks, and\n\tFaceDeteceFaceIds for each detected face.\n"},
	{"AeEnable", "AeEnable\n\nEnable or disable the AEGC algorith"
		"m. When this control is set to true,\nboth ExposureTimeMode "
		"and AnalogueGainMode are set to auto, and if this\ncontrol i"
		"s set to false then both are set to manual.\n\nIf ExposureTi"
		"meMode or AnalogueGainMode are also set in the same\nrequest"
		" as AeEnable, then the modes supplied by ExposureTimeMode or"
		"\nAnalogueGainMode will take precedence.\n\nSee also: Exposu"
		"reTimeMode AnalogueGainMode\n"},
	{"AeMeteringMode", "AeMeteringMode\n\nSpecify a metering mode"
		" for the AE algorithm to use.\n\nThe metering modes determin"
		"e which parts of the image are used to\ndetermine the scene "
		"brightness. Metering modes may be platform specific\nand not"
		" all metering modes may be supported.\n0\tCentre-weighted me"
		"tering mode.\n1\tSpot metering mode.\n2\tMatrix metering mod"
		"e.\n3\tCustom metering mode.\n"},
	{"AeConstraintMode", "AeConstraintMode\n\nSpecify a constrain"
		"t mode for the AE algorithm to use.\n\nThe constraint modes "
		"determine how the measured scene brightness is\nadjusted to "
		"reach the desired target exposure. Constraint modes may be\n"
		"platform specific, and not all constraint modes may be suppo"
		"rted.\n0\tDefault constraint mode.\n\t\n\tThis mode aims to "
		"balance the exposure of different parts of the\n\timage so a"
		"s to reach a reasonable average level. However, highlights\n"
		"\tin the image may appear over-exposed and lowlights may app"
		"ear\n\tunder-exposed.\n1\tHighlight constraint mode.\n\t\n\t"
		"This mode adjusts the exposure levels in order to try and av"
		"oid\n\tover-exposing the brightest parts (highlights) of an "
		"image.\n\tOther non-highlight parts of the image may appear "
		"under-exposed.\n2\tShadows constraint mode.\n\t\n\tThis mode"
		" adjusts the exposure levels in order to try and avoid\n\tun"
		"der-exposing the dark parts (shadows) of an image. Other nor"
		"mally\n\texposed parts of the image may appear over-exposed."
		"\n3\tCustom constraint mode.\n"},
	{"AeExposureMode", "AeExposureMode\n\nSpecify an exposure mod"
		"e for the AE algorithm to use.\n\nThe exposure modes specify"
		" how the desired total exposure is divided\nbetween the expo"
		"sure time and the sensor's analogue gain. They are\nplatform"
		" specific, and not all exposure modes may be supported.\n\nW"
		"hen one of AnalogueGainMode or ExposureTimeMode is set to Ma"
		"nual,\nthe fixed values will override any choices made by Ae"
		"ExposureMode.\n\nSee also: AnalogueGainMode\nSee also: Expos"
		"ureTimeMode\n0\tDefault exposure mode.\n1\tExposure mode all"
		"owing only short exposure times.\n2\tExposure mode allowing "
		"long exposure times.\n3\tCustom exposure mode.\n"},
	{"ExposureValue", "ExposureValue\n\nSpecify an Exposure Value"
		" (EV) parameter.\n\nThe EV parameter will only be applied if"
		" the AE algorithm is currently\nenabled, that is, at least o"
		"ne of AnalogueGainMode and ExposureTimeMode\nare in Auto mod"
		"e.\n\nBy convention EV adjusts the exposure as log2. For exa"
		"mple\nEV = [-2, -1, -0.5, 0, 0.5, 1, 2] results in an exposu"
		"re adjustment\nof [1/4x, 1/2x, 1/sqrt(2)x, 1x, sqrt(2)x, 2x,"
		" 4x].\n\nSee also: AnalogueGainMode\nSee also: ExposureTimeM"
		"ode\n"},
	{"ExposureTime", "ExposureTime\n\nExposure time for the frame"
		" applied in the sensor device.\n\nThis value is specified in"
		" microseconds.\n\nThis control will only take effect if Expo"
		"sureTimeMode is Manual. If\nthis control is set when Exposur"
		"eTimeMode is Auto, the value will be\nignored and will not b"
		"e retained.\n\nWhen reported in metadata, this control indic"
		"ates what exposure time\nwas used for the current frame, reg"
		"ardless of ExposureTimeMode.\nExposureTimeMode will indicate"
		" the source of the exposure time value,\nwhether it came fro"
		"m the AE algorithm or not.\n\nSee also: AnalogueGain\nSee al"
		"so: ExposureTimeMode\n"},
	{"ExposureTimeMode", "ExposureTimeMode\n\nControls the source"
		" of the exposure time that is applied to the image\nsensor."
		"\n\nWhen set to Auto, the AE algorithm computes the exposure"
		" time and\nconfigures the image sensor accordingly. When set"
		" to Manual, the value\nof the ExposureTime control is used."
		"\n\nWhen transitioning from Auto to Manual mode and no Expos"
		"ureTime control\nis provided by the application, the last va"
		"lue computed by the AE\nalgorithm when the mode was Auto wil"
		"l be used. If the ExposureTimeMode\nwas never set to Auto (e"
		"ither because the camera started in Manual mode,\nor Auto is"
		" not supported by the camera), the camera should use a\nbest"
		"-effort default value.\n\nIf ExposureTimeModeManual is suppo"
		"rted, the ExposureTime control must\nalso be supported.\n\nC"
		"ameras that support manual control of the sensor shall suppo"
		"rt manual\nmode for both ExposureTimeMode and AnalogueGainMo"
		"de, and shall expose\nthe ExposureTime and AnalogueGain cont"
		"rols. If the camera also has an\nAEGC implementation, both E"
		"xposureTimeMode and AnalogueGainMode shall\nsupport both man"
		"ual and auto mode. If auto mode is available, it shall\nbe t"
		"he default mode. These rules do not apply to black box camer"
		"as\nsuch as UVC cameras, where the available gain and exposu"
		"re modes are\ncompletely dependent on what the device expose"
		"s.\n\n\t Flickerless exposure mode transitions\n\nApplicatio"
		"ns that wish to transition from ExposureTimeModeAuto to dire"
		"ct\ncontrol of the exposure time without causing extra flick"
		"er can do so by\nselecting an ExposureTime value as close as"
		" possible to the last value\ncomputed by the auto exposure a"
		"lgorithm in order to avoid any visible\nflickering.\n\nTo se"
		"lect the correct value to use as ExposureTime value, applica"
		"tions\nshould accommodate the natural delay in applying cont"
		"rols caused by the\ncapture pipeline frame depth.\n\nWhen sw"
		"itching to manual exposure mode, applications should not\nim"
		"mediately specify an ExposureTime value in the same request "
		"where\nExposureTimeMode is set to Manual. They should instea"
		"d wait for the\nfirst Request where ExposureTimeMode is repo"
		"rted as\nExposureTimeModeManual in the Request metadata, and"
		" use the reported\nExposureTime to populate the control valu"
		"e in the next Request to be\nqueued to the Camera.\n\nThe im"
		"plementation of the auto-exposure algorithm should equally t"
		"ry to\nminimize flickering and when transitioning from manua"
		"l exposure mode to\nauto exposure use the last value provide"
		"d by the application as starting\npoint.\n\n1. Start with Ex"
		"posureTimeMode set to Auto\n\n2. Set ExposureTimeMode to Man"
		"ual\n\n3. Wait for the first completed request that has Expo"
		"sureTimeMode\nset to Manual\n\n4. Copy the value reported in"
		" ExposureTime into a new request, and\nsubmit it\n\n5. Proce"
		"ed to run manual exposure time as desired\n\nSee also: Expos"
		"ureTime\n0\tThe exposure time will be calculated automatical"
		"ly and set by the\n\tAE algorithm.\n\t\n\tIf ExposureTime is"
		" set while this mode is active, it will be\n\tignored, and i"
		"ts value will not be retained.\n\t\n\tWhen transitioning fro"
		"m Manual to Auto mode, the AEGC should start\n\tits adjustme"
		"nts based on the last set manual ExposureTime value.\n1\tThe"
		" exposure time will not be updated by the AE algorithm.\n\t"
		"\n\tWhen transitioning from Auto to Manual mode, the last co"
		"mputed\n\texposure value is used until a new value is specif"
		"ied through the\n\tExposureTime control. If an ExposureTime "
		"value is specified in the\n\tsame request where the Exposure"
		"TimeMode is changed from Auto to\n\tManual, the provided Exp"
		"osureTime is applied immediately.\n"},
	{"AnalogueGain", "AnalogueGain\n\nAnalogue gain value applied"
		" in the sensor device.\n\nThe value of the control specifies"
		" the gain multiplier applied to all\ncolour channels. This v"
		"alue cannot be lower than 1.0.\n\nThis control will only tak"
		"e effect if AnalogueGainMode is Manual. If\nthis control is "
		"set when AnalogueGainMode is Auto, the value will be\nignore"
		"d and will not be retained.\n\nWhen reported in metadata, th"
		"is control indicates what analogue gain\nwas used for the cu"
		"rrent request, regardless of AnalogueGainMode.\nAnalogueGain"
		"Mode will indicate the source of the analogue gain value,\nw"
		"hether it came from the AEGC algorithm or not.\n\nSee also: "
		"ExposureTime\nSee also: AnalogueGainMode\n"},
	{"AnalogueGainMode", "AnalogueGainMode\n\nControls the source"
		" of the analogue gain that is applied to the image\nsensor."
		"\n\nWhen set to Auto, the AEGC algorithm computes the analog"
		"ue gain and\nconfigures the image sensor accordingly. When s"
		"et to Manual, the value\nof the AnalogueGain control is used"
		".\n\nWhen transitioning from Auto to Manual mode and no Anal"
		"ogueGain control\nis provided by the application, the last v"
		"alue computed by the AEGC\nalgorithm when the mode was Auto "
		"will be used. If the AnalogueGainMode\nwas never set to Auto"
		" (either because the camera started in Manual mode,\nor Auto"
		" is not supported by the camera), the camera should use a\nb"
		"est-effort default value.\n\nIf AnalogueGainModeManual is su"
		"pported, the AnalogueGain control must\nalso be supported.\n"
		"\nFor cameras where we have control over the ISP, both Expos"
		"ureTimeMode\nand AnalogueGainMode are expected to support ma"
		"nual mode, and both\ncontrols (as well as ExposureTimeMode a"
		"nd AnalogueGain) are expected to\nbe present. If the camera "
		"also has an AEGC implementation, both\nExposureTimeMode and "
		"AnalogueGainMode shall support both manual and\nauto mode. I"
		"f auto mode is available, it shall be the default mode.\nThe"
		"se rules do not apply to black box cameras such as UVC camer"
		"as,\nwhere the available gain and exposure modes are complet"
		"ely dependent on\nwhat the hardware exposes.\n\nThe same pro"
		"cedure described for performing flickerless transitions in\n"
		"the ExposureTimeMode control documentation can be applied to"
		" analogue\ngain.\n\nSee also: ExposureTimeMode\nSee also: An"
		"alogueGain\n0\tThe analogue gain will be calculated automati"
		"cally and set by the\n\tAEGC algorithm.\n\t\n\tIf AnalogueGa"
		"in is set while this mode is active, it will be\n\tignored, "
		"and it will also not be retained.\n\t\n\tWhen transitioning "
		"from Manual to Auto mode, the AEGC should start\n\tits adjus"
		"tments based on the last set manual AnalogueGain value.\n1\t"
		"The analogue gain will not be updated by the AEGC algorithm."
		"\n\t\n\tWhen transitioning from Auto to Manual mode, the las"
		"t computed\n\tgain value is used until a new value is specif"
		"ied through the\n\tAnalogueGain control. If an AnalogueGain "
		"value is specified in the\n\tsame request where the Analogue"
		"GainMode is changed from Auto to\n\tManual, the provided Ana"
		"logueGain is applied immediately.\n"},
	{"AeFlickerMode", "AeFlickerMode\n\nSet the flicker avoidance"
		" mode for AGC/AEC.\n\nThe flicker mode determines whether, a"
		"nd how, the AGC/AEC algorithm\nattempts to hide flicker effe"
		"cts caused by the duty cycle of artificial\nlighting.\n\nAlt"
		"hough implementation dependent, many algorithms for \"flicke"
		"r\navoidance\" work by restricting this exposure time to int"
		"eger multiples\nof the cycle period, wherever possible.\n\nI"
		"mplementations may not support all of the flicker modes list"
		"ed below.\n\nBy default the system will start in FlickerAuto"
		" mode if this is\nsupported, otherwise the flicker mode will"
		" be set to FlickerOff.\n0\tNo flicker avoidance is performed"
		".\n1\tManual flicker avoidance.\n\t\n\tSuppress flicker effe"
		"cts caused by lighting running with a period\n\tspecified by"
		" the AeFlickerPeriod control.\n\tSee also: AeFlickerPeriod\n"
		"2\tAutomatic flicker period detection and avoidance.\n\t\n\t"
		"The system will automatically determine the most likely valu"
		"e of\n\tflicker period, and avoid flicker of this frequency."
		" Once flicker\n\tis being corrected, it is implementation de"
		"pendent whether the\n\tsystem is still able to detect a chan"
		"ge in the flicker period.\n\tSee also: AeFlickerDetected\n"},
	{"AeFlickerPeriod", "AeFlickerPeriod\n\nManual flicker period"
		" in microseconds.\n\nThis value sets the current flicker per"
		"iod to avoid. It is used when\nAeFlickerMode is set to Flick"
		"erManual.\n\nTo cancel 50Hz mains flicker, this should be se"
		"t to 10000 (corresponding\nto 100Hz), or 8333 (120Hz) for 60"
		"Hz mains.\n\nSetting the mode to FlickerManual when no AeFli"
		"ckerPeriod has ever been\nset means that no flicker cancella"
		"tion occurs (until the value of this\ncontrol is updated).\n"
		"\nSwitching to modes other than FlickerManual has no effect "
		"on the\nvalue of the AeFlickerPeriod control.\n\nSee also: A"
		"eFlickerMode\n"},
	{"Brightness", "Brightness\n\nSpecify a fixed brightness para"
		"meter.\n\nPositive values (up to 1.0) produce brighter image"
		"s; negative values\n(up to -1.0) produce darker images and 0"
		".0 leaves pixels unchanged.\n"},
	{"Contrast", "Contrast\n\nSpecify a fixed contrast parameter."
		"\n\nNormal contrast is given by the value 1.0; larger values"
		" produce images\nwith more contrast.\n"},
	{"AwbEnable", "AwbEnable\n\nEnable or disable the AWB.\n\nWhe"
		"n AWB is enabled, the algorithm estimates the colour tempera"
		"ture of\nthe scene and computes colour gains and the colour "
		"correction matrix\nautomatically. The computed colour temper"
		"ature, gains and correction\nmatrix are reported in metadata"
		". The corresponding controls are ignored\nif set in a reques"
		"t.\n\nWhen AWB is disabled, the colour temperature, gains an"
		"d correction\nmatrix are not updated automatically and can b"
		"e set manually in\nrequests.\n\nSee also: ColourCorrectionMa"
		"trix\nSee also: ColourGains\nSee also: ColourTemperature\n"},
	{"AwbMode", "AwbMode\n\nSpecify the range of illuminants to u"
		"se for the AWB algorithm.\n\nThe modes supported are platfor"
		"m specific, and not all modes may be\nsupported.\n0\tSearch "
		"over the whole colour temperature range.\n1\tIncandescent AW"
		"B lamp mode.\n2\tTungsten AWB lamp mode.\n3\tFluorescent AWB"
		" lamp mode.\n4\tIndoor AWB lighting mode.\n5\tDaylight AWB l"
		"ighting mode.\n6\tCloudy AWB lighting mode.\n7\tCustom AWB m"
		"ode.\n"},
	{"ColourGains", "ColourGains\n\nPair of gain values for the R"
		"ed and Blue colour channels, in that\norder.\n\nColourGains "
		"can only be applied in a Request when the AWB is disabled.\n"
		"If ColourGains is set in a request but ColourTemperature is "
		"not, the\nimplementation shall calculate and set the ColourT"
		"emperature based on\nthe ColourGains.\n\nSee also: AwbEnable"
		"\nSee also: ColourTemperature\n"},
	{"Saturation", "Saturation\n\nSpecify a fixed saturation para"
		"meter.\n\nNormal saturation is given by the value 1.0; large"
		"r values produce more\nsaturated colours; 0.0 produces a gre"
		"yscale image.\n"},
	{"Sharpness", "Sharpness\n\nIntensity of the sharpening appli"
		"ed to the image.\n\nA value of 0.0 means no sharpening. The "
		"minimum value means\nminimal sharpening, and shall be 0.0 un"
		"less the camera can't\ndisable sharpening completely. The de"
		"fault value shall give a\n\"reasonable\" level of sharpening"
		", suitable for most use cases.\nThe maximum value may apply "
		"extremely high levels of sharpening,\nhigher than anyone cou"
		"ld reasonably want. Negative values are\nnot allowed. Note a"
		"lso that sharpening is not applied to raw\nstreams.\n"},
	{"ColourCorrectionMatrix", "ColourCorrectionMatrix\n\nThe 3x3"
		" matrix that converts camera RGB to sRGB within the imaging"
		"\npipeline.\n\nThis should describe the matrix that is used "
		"after pixels have been\nwhite-balanced, but before any gamma"
		" transformation. The 3x3 matrix is\nstored in conventional r"
		"eading order in an array of 9 floating point\nvalues.\n\nCol"
		"ourCorrectionMatrix can only be applied in a Request when th"
		"e AWB is\ndisabled.\n\nSee also: AwbEnable\nSee also: Colour"
		"Temperature\n"},
	{"ScalerCrop", "ScalerCrop\n\nSets the image portion that wil"
		"l be scaled to form the whole of\nthe final output image.\n"
		"\nThe (x,y) location of this rectangle is relative to the\nP"
		"ixelArrayActiveAreas that is being used. The units remain na"
		"tive\nsensor pixels, even if the sensor is being used in a b"
		"inning or\nskipping mode.\n\nThis control is only present wh"
		"en the pipeline supports scaling. Its\nmaximum valid value i"
		"s given by the properties::ScalerCropMaximum\nproperty, and "
		"the two can be used to implement digital zoom.\n"},
	{"DigitalGain", "DigitalGain\n\nDigital gain value applied du"
		"ring the processing steps applied\nto the image as captured "
		"from the sensor.\n\nThe global digital gain factor is applie"
		"d to all the colour channels\nof the RAW image. Different pi"
		"peline models are free to\nspecify how the global gain facto"
		"r applies to each separate\nchannel.\n\nIf an imaging pipeli"
		"ne applies digital gain in distinct\nprocessing steps, this "
		"value indicates their total sum.\nPipelines are free to deci"
		"de how to adjust each processing\nstep to respect the receiv"
		"ed gain factor and shall report\ntheir total value in the re"
		"quest metadata.\n"},
	{"FrameDurationLimits", "FrameDurationLimits\n\nThe minimum a"
		"nd maximum (in that order) frame duration, expressed in\nmic"
		"roseconds.\n\nWhen provided by applications, the control spe"
		"cifies the sensor frame\nduration interval the pipeline has "
		"to use. This limits the largest\nexposure time the sensor ca"
		"n use. For example, if a maximum frame\nduration of 33ms is "
		"requested (corresponding to 30 frames per second),\nthe sens"
		"or will not be able to raise the exposure time above 33ms.\n"
		"A fixed frame duration is achieved by setting the minimum an"
		"d maximum\nvalues to be the same. Setting both values to 0 r"
		"everts to using the\ncamera defaults.\n\nThe maximum frame d"
		"uration provides the absolute limit to the exposure\ntime co"
		"mputed by the AE algorithm and it overrides any exposure mod"
		"e\nsetting specified with controls::AeExposureMode. Similarl"
		"y, when a\nmanual exposure time is set through controls::Exp"
		"osureTime, it also\ngets clipped to the limits set by this c"
		"ontrol. When reported in\nmetadata, the control expresses th"
		"e minimum and maximum frame durations\nused after being clip"
		"ped to the sensor provided frame duration limits.\n\nSee als"
		"o: AeExposureMode\nSee also: ExposureTime\n\n\todo Define ho"
		"w to calculate the capture frame rate by\ndefining controls "
		"to report additional delays introduced by\nthe capture pipel"
		"ine or post-processing stages (ie JPEG\nconversion, frame sc"
		"aling).\n\n\todo Provide an explicit definition of default c"
		"ontrol values, for\nthis and all other controls.\n"},
	{"AfMode", "AfMode\n\nThe mode of the AF (autofocus) algorith"
		"m.\n\nAn implementation may choose not to implement all the "
		"modes.\n0\tThe AF algorithm is in manual mode.\n\t\n\tIn thi"
		"s mode it will never perform any action nor move the lens of"
		"\n\tits own accord, but an application can specify the desir"
		"ed lens\n\tposition using the LensPosition control. The AfSt"
		"ate will always\n\treport AfStateIdle.\n\t\n\tIf the camera "
		"is started in AfModeManual, it will move the focus\n\tlens t"
		"o the position specified by the LensPosition control.\n\t\n"
		"\tThis mode is the recommended default value for the AfMode "
		"control.\n\tExternal cameras (as reported by the Location pr"
		"operty set to\n\tCameraLocationExternal) may use a different"
		" default value.\n1\tThe AF algorithm is in auto mode.\n\t\n"
		"\tIn this mode the algorithm will never move the lens or cha"
		"nge state\n\tunless the AfTrigger control is used. The AfTri"
		"gger control can be\n\tused to initiate a focus scan, the re"
		"sults of which will be\n\treported by AfState.\n\t\n\tIf the"
		" autofocus algorithm is moved from AfModeAuto to another mod"
		"e\n\twhile a scan is in progress, the scan is cancelled imme"
		"diately,\n\twithout waiting for the scan to finish.\n\t\n\tW"
		"hen first entering this mode the AfState will report AfState"
		"Idle.\n\tWhen a trigger control is sent, AfState will report"
		" AfStateScanning\n\tfor a period before spontaneously changi"
		"ng to AfStateFocused or\n\tAfStateFailed, depending on the o"
		"utcome of the scan. It will remain\n\tin this state until an"
		"other scan is initiated by the AfTrigger\n\tcontrol. If a sc"
		"an is cancelled (without changing to another mode),\n\tAfSta"
		"te will return to AfStateIdle.\n2\tThe AF algorithm is in co"
		"ntinuous mode.\n\t\n\tIn this mode the lens can re-start a s"
		"can spontaneously at any\n\tmoment, without any user interve"
		"ntion. The AfState still reports\n\twhether the algorithm is"
		" currently scanning or not, though the\n\tapplication has no"
		" ability to initiate or cancel scans, nor to move\n\tthe len"
		"s for itself.\n\t\n\tHowever, applications can pause the AF "
		"algorithm from continuously\n\tscanning by using the AfPause"
		" control. This allows video or still\n\timages to be capture"
		"d whilst guaranteeing that the focus is fixed.\n\t\n\tWhen s"
		"et to AfModeContinuous, the system will immediately initiate"
		" a\n\tscan so AfState will report AfStateScanning, and will "
		"settle on one\n\tof AfStateFocused or AfStateFailed, dependi"
		"ng on the scan result.\n"},
	{"AfRange", "AfRange\n\nThe range of focus distances that is "
		"scanned.\n\nAn implementation may choose not to implement al"
		"l the options here.\n0\tA wide range of focus distances is s"
		"canned.\n\t\n\tScanned distances cover all the way from infi"
		"nity down to close\n\tdistances, though depending on the imp"
		"lementation, possibly not\n\tincluding the very closest macr"
		"o positions.\n1\tOnly close distances are scanned.\n2\tThe f"
		"ull range of focus distances is scanned.\n\t\n\tThis range i"
		"s similar to AfRangeNormal but includes the very\n\tclosest "
		"macro positions.\n"},
	{"AfSpeed", "AfSpeed\n\nDetermine whether the AF is to move t"
		"he lens as quickly as possible or\nmore steadily.\n\nFor exa"
		"mple, during video recording it may be desirable not to move"
		" the\nlens too abruptly, but when in a preview mode (waiting"
		" for a still\ncapture) it may be helpful to move the lens as"
		" quickly as is reasonably\npossible.\n0\tMove the lens at it"
		"s usual speed.\n1\tMove the lens more quickly.\n"},
	{"AfMetering", "AfMetering\n\nThe parts of the image used by "
		"the AF algorithm to measure focus.\n0\tLet the AF algorithm "
		"decide for itself where it will measure focus.\n1\tUse the r"
		"ectangles defined by the AfWindows control to measure focus."
		"\n\t\n\tIf no windows are specified the behaviour is platfor"
		"m dependent.\n"},
	{"AfWindows", "AfWindows\n\nThe focus windows used by the AF "
		"algorithm when AfMetering is set to\nAfMeteringWindows.\n\nT"
		"he units used are pixels within the rectangle returned by th"
		"e\nScalerCropMaximum property.\n\nIn order to be activated, "
		"a rectangle must be programmed with non-zero\nwidth and heig"
		"ht. Internally, these rectangles are intersected with the\nS"
		"calerCropMaximum rectangle. If the window becomes empty afte"
		"r this\noperation, then the window is ignored. If all the wi"
		"ndows end up being\nignored, then the behaviour is platform "
		"dependent.\n\nOn platforms that support the ScalerCrop contr"
		"ol (for implementing\ndigital zoom, for example), no automat"
		"ic recalculation or adjustment of\nAF windows is performed i"
		"nternally if the ScalerCrop is changed. If any\nwindow lies "
		"outside the output image after the scaler crop has been\napp"
		"lied, it is up to the application to recalculate them.\n\nTh"
		"e details of how the windows are used are platform dependent"
		". We note\nthat when there is more than one AF window, a typ"
		"ical implementation\nmight find the optimal focus position f"
		"or each one and finally select\nthe window where the focal d"
		"istance for the objects shown in that part\nof the image are"
		" closest to the camera.\n"},
	{"AfTrigger", "AfTrigger\n\nStart an autofocus scan.\n\nThis "
		"control starts an autofocus scan when AfMode is set to AfMod"
		"eAuto,\nand is ignored if AfMode is set to AfModeManual or A"
		"fModeContinuous. It\ncan also be used to terminate a scan ea"
		"rly.\n0\tStart an AF scan.\n\t\n\tSetting the control to AfT"
		"riggerStart is ignored if a scan is in\n\tprogress.\n1\tCanc"
		"el an AF scan.\n\t\n\tThis does not cause the lens to move a"
		"nywhere else. Ignored if no\n\tscan is in progress.\n"},
	{"AfPause", "AfPause\n\nPause lens movements when in continuo"
		"us autofocus mode.\n\nThis control has no effect except when"
		" in continuous autofocus mode\n(AfModeContinuous). It can be"
		" used to pause any lens movements while\n(for example) image"
		"s are captured. The algorithm remains inactive\nuntil it is "
		"instructed to resume.\n0\tPause the continuous autofocus alg"
		"orithm immediately.\n\t\n\tThe autofocus algorithm is paused"
		" whether or not any kind of scan\n\tis underway. AfPauseStat"
		"e will subsequently report\n\tAfPauseStatePaused. AfState ma"
		"y report any of AfStateScanning,\n\tAfStateFocused or AfStat"
		"eFailed, depending on the algorithm's state\n\twhen it recei"
		"ved this control.\n1\tPause the continuous autofocus algorit"
		"hm at the end of the scan.\n\t\n\tThis is similar to AfPause"
		"Immediate, and if the AfState is\n\tcurrently reporting AfSt"
		"ateFocused or AfStateFailed it will remain\n\tin that state "
		"and AfPauseState will report AfPauseStatePaused.\n\t\n\tHowe"
		"ver, if the algorithm is scanning (AfStateScanning),\n\tAfPa"
		"useState will report AfPauseStatePausing until the scan is\n"
		"\tfinished, at which point AfState will report one of AfStat"
		"eFocused\n\tor AfStateFailed, and AfPauseState will change t"
		"o\n\tAfPauseStatePaused.\n2\tResume continuous autofocus ope"
		"ration.\n\t\n\tThe algorithm starts again from exactly where"
		" it left off, and\n\tAfPauseState will report AfPauseStateRu"
		"nning.\n"},
	{"LensPosition", "LensPosition\n\nSet and report the focus le"
		"ns position.\n\nThis control instructs the lens to move to a"
		" particular position and\nalso reports back the position of "
		"the lens for each frame.\n\nThe LensPosition control is igno"
		"red unless the AfMode is set to\nAfModeManual, though the va"
		"lue is reported back unconditionally in all\nmodes.\n\nThis "
		"value, which is generally a non-integer, is the reciprocal o"
		"f the\nfocal distance in metres, also known as dioptres. Tha"
		"t is, to set a\nfocal distance D, the lens position LP is gi"
		"ven by\n\nFP = 1m/D\n\nFor example:\n\n- 0 moves the lens to"
		" infinity.\n- 0.5 moves the lens to focus on objects 2m away"
		".\n- 2 moves the lens to focus on objects 50cm away.\n- And "
		"larger values will focus the lens closer.\n\nThe default val"
		"ue of the control should indicate a good general\nposition f"
		"or the lens, often corresponding to the hyperfocal distance"
		"\n(the closest position for which objects at infinity are st"
		"ill\nacceptably sharp). The minimum will often be zero (mean"
		"ing infinity),\nand the maximum value defines the closest fo"
		"cus position.\n\n\todo Define a property to report the Hyper"
		"focal distance of calibrated\nlenses.\n"},
	{"HdrMode", "HdrMode\n\nSet the mode to be used for High Dyna"
		"mic Range (HDR) imaging.\n\nHDR techniques typically include"
		" multiple exposure, image fusion and\ntone mapping technique"
		"s to improve the dynamic range of the resulting\nimages.\n\n"
		"When using an HDR mode, images are captured with different s"
		"ets of AGC\nsettings called HDR channels. Channels indicate "
		"in particular the type\nof exposure (short, medium or long) "
		"used to capture the raw image,\nbefore fusion. Each HDR imag"
		"e is tagged with the corresponding channel\nusing the HdrCha"
		"nnel control.\n\nSee also: HdrChannel\n0\tHDR is disabled.\n"
		"\t\n\tMetadata for this frame will not include the HdrChanne"
		"l control.\n1\tMultiple exposures will be generated in an al"
		"ternating fashion.\n\t\n\tThe multiple exposures will not be"
		" merged together and will be\n\treturned to the application "
		"as they are. Each image will be tagged\n\twith the correct H"
		"DR channel, indicating what kind of exposure it\n\tis. The t"
		"ag should be the same as in the HdrModeMultiExposure case.\n"
		"\t\n\tThe expectation is that an application using this mode"
		" would merge\n\tthe frames to create HDR images for itself i"
		"f it requires them.\n2\tMultiple exposures will be generated"
		" and merged to create HDR\n\timages.\n\t\n\tEach image will "
		"be tagged with the HDR channel (long, medium or\n\tshort) th"
		"at arrived and which caused this image to be output.\n\t\n\t"
		"Systems that use two channels for HDR will return images tag"
		"ged\n\talternately as the short and long channel. Systems th"
		"at use three\n\tchannels for HDR will cycle through the shor"
		"t, medium and long\n\tchannel before repeating.\n3\tMultiple"
		" frames all at a single exposure will be used to create HDR"
		"\n\timages.\n\t\n\tThese images should be reported as all co"
		"rresponding to the HDR\n\tshort channel.\n4\tMultiple frames"
		" will be combined to produce \"night mode\" images.\n\t\n\tI"
		"t is up to the implementation exactly which HDR channels it "
		"uses,\n\tand the images will all be tagged accordingly with "
		"the correct HDR\n\tchannel information.\n"},
	{"Gamma", "Gamma\n\nSpecify a fixed gamma value.\n\nThe defau"
		"lt gamma value must be 2.2 which closely mimics sRGB gamma."
		"\nNote that this is camera gamma, so it is applied as 1.0/ga"
		"mma.\n"},
	{"DebugMetadataEnable", "DebugMetadataEnable\n\nEnable or dis"
		"able the debug metadata.\n"},
	{"WdrMode", "WdrMode\n\nSet the WDR mode.\n\nThe WDR mode is "
		"used to select the algorithm used for global tone\nmapping. "
		"It will automatically reduce the exposure time of the sensor"
		"\nso that there are only a small number of saturated pixels "
		"in the image.\nThe algorithm then compensates for the loss o"
		"f brightness by applying a\nglobal tone mapping curve to the"
		" image.\n0\tWdr is disabled.\n1\tApply a linear global tone "
		"mapping curve.\n\tA curve with two linear sections is applie"
		"d. This produces good results at the expense of a slightly a"
		"rtificial look.\n2\tApply a power global tone mapping curve."
		"\n\t\n\tThis curve has high gain values on the dark areas of"
		" an image and\n\thigh compression values on the bright area."
		" It therefore tends to\n\tproduce noticeable noise artifacts"
		".\n3\tApply an exponential global tone mapping curve.\n\t\n"
		"\tThis curve has lower gain values in dark areas compared to"
		" the power\n\tcurve but produces a more natural look compare"
		"d to the linear curve.\n\tIt is therefore the best choice fo"
		"r most scenes.\n4\tApply histogram equalization.\n\t\n\tThis"
		" curve preserves most of the information of the image at the"
		"\n\texpense of a very artificial look. It is therefore best "
		"suited for\n\ttechnical analysis.\n"},
	{"WdrStrength", "WdrStrength\n\nSpecify the strength of the w"
		"dr algorithm. The exact meaning of this\nvalue is specific t"
		"o the algorithm in use. Usually a value of 0 means no\ngloba"
		"l tone mapping is applied. A values of 1 is the default valu"
		"e and\nthe correct value for most scenes. A value above 1 in"
		"creases the global\ntone mapping effect and can lead to unre"
		"alistic image effects.\n"},
	{"WdrMaxBrightPixels", "WdrMaxBrightPixels\n\nPercentage of a"
		"llowed (nearly) saturated pixels. The WDR algorithm\nreduces"
		" the WdrExposureValue until the amount of pixels that are cl"
		"ose\nto saturation is lower than this value.\n"},
	{"LensDewarpEnable", "LensDewarpEnable\n\nEnable or disable l"
		"ens dewarping.\n"},
	{"LensShadingCorrectionEnable", "LensShadingCorrectionEnable"
		"\n\nEnable or disable the lens shading correction.\n"},
	{"StatsOutputEnable", "StatsOutputEnable\n\nToggles the Raspb"
		"erry Pi IPA to output the hardware generated statistics.\n\n"
		"When this control is set to true, the IPA outputs a binary d"
		"ump of the\nhardware generated statistics through the Reques"
		"t metadata in the\nBcm2835StatsOutput control.\n\nSee also: "
		"Bcm2835StatsOutput\n"},
	{"ScalerCrops", "ScalerCrops\n\nAn array of rectangles, where"
		" each singular value has identical\nfunctionality to the Sca"
		"lerCrop control. This control allows the\nRaspberry Pi pipel"
		"ine handler to control individual scaler crops per\noutput s"
		"tream.\n\nThe order of rectangles passed into the control mu"
		"st match the order of\nstreams configured by the application"
		". The pipeline handler will only\nconfigure crop retangles u"
		"p-to the number of output streams configured.\nAll subsequen"
		"t rectangles passed into this control are ignored by the\npi"
		"peline handler.\n\nIf both rpi::ScalerCrops and ScalerCrop c"
		"ontrols are present in a\nControlList, the latter is discard"
		"ed, and crops are obtained from this\ncontrol.\n\nNote that "
		"using different crop rectangles for each output stream with"
		"\nthis control is only applicable on the Pi5/PiSP platform. "
		"This control\nshould also be considered temporary/draft and "
		"will be replaced with\nofficial libcamera API support for pe"
		"r-stream controls in the future.\n\nSee also: ScalerCrop\n"},
	{"SyncMode", "SyncMode\n\nEnable or disable camera synchronis"
		"ation (\"sync\") mode.\n\nWhen sync mode is enabled, a camer"
		"a will synchronise frames temporally\nwith other cameras, ei"
		"ther attached to the same device or a different\none. There "
		"should be one \"server\" device, which broadcasts timing\nin"
		"formation to one or more \"clients\". Communication is one-w"
		"ay, from\nserver to clients only, and it is only clients tha"
		"t adjust their frame\ntimings to match the server.\n\nSync m"
		"ode requires all cameras to be running at (as far as possibl"
		"e) the\nsame fixed framerate. Clients may continue to make a"
		"djustments to keep\ntheir cameras synchronised with the serv"
		"er for the duration of the\nsession, though any updates afte"
		"r the initial ones should remain small.\n\nSee also: SyncRea"
		"dy\nSee also: SyncTimer\nSee also: SyncFrames\n0\tDisable sy"
		"nc mode.\n1\tEnable sync mode, act as server. The server bro"
		"adcasts timing\n\tmessages to any clients that are listening"
		", so that the clients can\n\tsynchronise their camera frames"
		" with the server's.\n2\tEnable sync mode, act as client. A c"
		"lient listens for any server\n\tmessages, and arranges for i"
		"ts camera frames to synchronise as\n\tclosely as possible wi"
		"th the server's. Many clients can listen out\n\tfor the same"
		" server. Clients can also be started ahead of any\n\tservers"
		", causing them merely to wait for the server to start.\n"},
	{"SyncFrames", "SyncFrames\n\nThe number of frames the server"
		" should wait, after enabling\nSyncModeServer, before signall"
		"ing (via the SyncReady control) that\nframes should be used."
		" This therefore determines the \"ready time\" for\nall synch"
		"ronised cameras.\n\nThis control value should be set only fo"
		"r the device that is to act as\nthe server, before or at the"
		" same moment at which SyncModeServer is\nenabled.\n\nSee als"
		"o: SyncMode\nSee also: SyncReady\nSee also: SyncTimer\n"},
	{"CnnEnableInputTensor", "CnnEnableInputTensor\n\nBoolean to "
		"control if the IPA returns the input tensor used by the CNN"
		"\nto generate the output tensors via the CnnInputTensor cont"
		"rol. Because\nthe input tensor may be relatively large, for "
		"efficiency reason avoid\nenabling input tensor output unless"
		" required for debugging purposes.\n\nSee also: CnnInputTenso"
		"r\n"},
};
